### ISSUE TITLE
迁移aw-soc和d1-rom-rt项目到gitee.com/rustsbi组织下

### ISSUE THREAD

**Issue by luojia65** [rustsbi/standalone#18]
贡献者们好！
由于项目发展需求，本项目的aw-soc和d1-rom-rt模块需要迁移到gitee.com/rustsbi账户下。两个新模块将是独立的仓库，并且由本仓库的贡献者维护。
出于开源社区的惯例，由于rustsbi/standalone项目并未与贡献者签署贡献者协议（CLA），所以本次项目迁移需要参与过两个模块开发的所有贡献者同意。他们是：@gaochengbo、@luojia65。
若同意，请在本issue下回复以下内容：
> 我同意将aw-soc和d1-rom-rt模块迁移到gitee.com/rustsbi下，并由@luojia65和@gaochengbo负责维护。

感谢各位的一路支持！

**Comment by gaochengbo** [comment]
okay

**Comment by luojia65** [comment]
感谢！我们即将开始项目的迁移工作。
